### ISSUE TITLE
[BUG] Website Not working?

### ISSUE THREAD

**Issue by asdsyd** [commclassroom/commclassroom.github.io#11]
![Screenshot 2022-10-14 at 12 10 01 PM](https://user-images.githubusercontent.com/77977076/195779588-5a095164-476d-438c-aeb9-39feeb495fe7.png)
It's redirecting to this page.

**Comment by VishwaS-22** [comment]
@asdsyd Yeah bro for me too its not working. Waiting to resolve this issue, because wanna check Roadmap.

**Comment by AnuragThePathak** [comment]
@VishwaS-22 you can obtain the roadmap here too https://github.com/commclassroom/roadmaps, it uses markdown.

**Comment by AnuragThePathak** [comment]
Website now up in https://commclassroom.github.io

**Comment by iadnankarim** [comment]
> Website now up in https://commclassroom.github.io

Site is still down I think you should change server 🙂
