### ISSUE TITLE
Update README mentioning the first version is being created by the team members only.

### ISSUE THREAD

**Issue by AnuragThePathak** [commclassroom/commclassroom.github.io#17]
The team members of Community Classroom are currently working on the first version of the Community Classroom website. Until it's ready and released, pull requests from anyone outside the team won't be accepted.

This information should be added to the README so that people can know it upon their visit to this repository.

**Comment by rakeshdeka** [comment]
Can I work on this issue?

**Comment by AnuragThePathak** [comment]
@rakeshdeka I just came to know that the first version is almost ready hence doing so is not required now. In fact, site is sent to production just now released officially.
